// _blind_pack.js — assemble the BLIND reading pack. Reads the two arm outputs, assigns A/B at random,
// writes (1) a provenance-free reading doc and (2) a SEALED key file. Per Roman's protocol: read cold,
// score per scene, pick a winner, THEN reveal.
//
//   node _blind_pack.js            -> _blind_out/reading_pack.md  +  _blind_out/KEY.sealed.json
//   node _blind_pack.js --reveal   -> prints the key
const fs = require('fs');
const OUT = '_blind_out';
const KEY = OUT + '/KEY.sealed.json';

if (process.argv.includes('--reveal')) {
  if (!fs.existsSync(KEY)) { console.error('no key file — run the pack first'); process.exit(1); }
  const k = JSON.parse(fs.readFileSync(KEY, 'utf8'));
  console.log('\n═══ REVEAL ═══');
  Object.entries(k.map).forEach(([label, arm]) =>
    console.log(`  Issue ${label}  =  ${arm === 'gen' ? 'MACHINE-GENERATED spine (world sim → IR → concrete enumerator → windowed schedule)' : 'HAND-AUTHORED spine (STARTER_PLANS, app.js:121191)'}`));
  console.log(`\n  sealed at: ${k.sealedAt}\n`);
  process.exit(0);
}

const arms = ['gen', 'hand'].map(a => {
  const p = `/tmp/arm_${a}.json`;
  if (!fs.existsSync(p)) { console.error(`MISSING ${p} — run: SPINE=${a} node _render_arm.js`); process.exit(1); }
  const d = JSON.parse(fs.readFileSync(p, 'utf8'));
  if (!d.complete) console.error(`WARN arm ${a} is marked incomplete (${d.capturedScenes}/${d.target})`);
  return { arm: a, scenes: (d.scenes || []).map(s => ({ idx: s.n, text: String(s.text || ''), action: s.action, dialogue: s.dialogue })) };
});

const short = arms.filter(a => a.scenes.length < 20);
if (short.length) short.forEach(a => console.error(`WARN arm ${a.arm} has ${a.scenes.length}/20 scenes — incomplete`));

// coin-flip the labels so neither the order nor the filename leaks provenance
const flip = Math.random() < 0.5;
const labelOf = { [flip ? 'A' : 'B']: 'gen', [flip ? 'B' : 'A']: 'hand' };
fs.mkdirSync(OUT, { recursive: true });
fs.writeFileSync(KEY, JSON.stringify({ map: labelOf, sealedAt: new Date().toISOString() }, null, 2));

const byArm = Object.fromEntries(arms.map(a => [a.arm, a]));
const strip = t => String(t || '')
  .replace(/<[^>]+>/g, '')            // the capture hook stores rendered HTML
  // The capture point is upstream of display, so raw authoring metadata is still attached.
  // It is not prose and would distract the blind read — strip [TITLE:…] / [SYNOPSIS:…] / [CHARACTERS:…].
  .replace(/^\s*\[(?:TITLE|SYNOPSIS|CHARACTERS|BEAT|SCENE)\s*:[^\]]*\]\s*$/gim, '')
  .replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&#39;|&rsquo;/g, "'")
  .replace(/&quot;|&ldquo;|&rdquo;/g, '"').replace(/&mdash;/g, '—')
  .replace(/\n{3,}/g, '\n\n').trim();

let md = `# Blind read — two issues of *The First Sacrifice*\n\n`;
md += `Same seed, same canon, same cast (Lirael / Julian), same author and prose settings, same 20 scenes,\n`;
md += `same player inputs. **One variable differs: where each scene's goal came from.** Which is which is sealed.\n\n`;
md += `Scene 1 is generated by the opening-template path in both issues (it does not read the spine), so the\n`;
md += `comparison really begins at scene 2.\n\n`;
md += `## How to score\n\n`;
md += `Per scene: **would I click Next? y / n** — and flag it if it feels *repetitive, procedural, inert, or like connective tissue*.\n`;
md += `At the end: **which issue would I voluntarily keep reading — A, B, or tie?** Then run \`node _blind_pack.js --reveal\`.\n\n`;
md += `---\n\n`;

for (const label of ['A', 'B']) {
  const a = byArm[labelOf[label]];
  md += `\n# ISSUE ${label}\n\n`;
  a.scenes.forEach(s => {
    md += `\n## ${label}·${s.idx}\n\n`;
    if (s.idx > 1 && s.action) md += `> *player:* ${s.action}${s.dialogue ? ` — "${s.dialogue}"` : ''}\n\n`;
    md += strip(s.text) + `\n\n`;
    md += `\`click Next? y / n\`  ·  \`flag: repetitive / procedural / inert / connective\`\n\n---\n`;
  });
}
md += `\n\n## Verdict\n\n- Issue A — scenes you'd click Next on: ___ / 20\n- Issue B — scenes you'd click Next on: ___ / 20\n- **Would keep reading: A / B / tie**\n\nThen: \`node _blind_pack.js --reveal\`\n`;

fs.writeFileSync(OUT + '/reading_pack.md', md);
fs.writeFileSync(OUT + '/blind_scenes.json', JSON.stringify(
  { A: byArm[labelOf.A].scenes.map(s => ({ ...s, text: strip(s.text) })),
    B: byArm[labelOf.B].scenes.map(s => ({ ...s, text: strip(s.text) })) }, null, 2));

// Deliberately do NOT print per-label word counts: combined with any per-ARM count printed elsewhere,
// they map label→provenance and break the blind. Scene counts only.
console.log(`\nBLIND PACK WRITTEN → ${OUT}/reading_pack.md`);
console.log(`  Issue A: ${byArm[labelOf.A].scenes.length} scenes`);
console.log(`  Issue B: ${byArm[labelOf.B].scenes.length} scenes`);
console.log(`  key sealed → ${KEY}  (reveal with: node _blind_pack.js --reveal)\n`);
