// REAL Book-1 → Book-2 continuity harness. Drives the ACTUAL startBook2() path headless via the
// guarded _book2TestBypass hooks, so Book-2 Scene-1 is generated by the real bespoke continuation
// callChat (NOT the scaffold). Inspects: cliffhanger continuity, no-deck, no-backstory-reintro,
// carried memory (demand_hint/goal_relationship), applied silent_apply, issueIndexInRun bump, F1 leak.
// Build-only: run costs ~3 LLM calls (title + blurb + Scene-1). Fire only with an explicit go.
const { chromium } = require('playwright-core');
const fs = require('fs');
const OUT = '/tmp/cont_result.json';
function log(...a){ console.error(...a); }

// A distinctive Book-1 cliffhanger — the tokens below let us test whether Book-2 Scene-1 continues it.
const CLIFF = "Book 1 ended mid-crisis on the rooftop of the Aldridge building: Mara had just discovered Dorian secretly bought her family's failing flower-import company, and the foundation board votes tomorrow on whether to liquidate it. They kissed for the first time as her phone lit up with the leaked audit files. The relationship is raw, unresolved, and electric; the looming threat is the board vote and the leak spreading through the donor list.";
const CONT_TOKENS = ['board', 'liquidat', 'leak', 'audit', 'rooftop', 'flower-import', 'Aldridge', 'donor'];

(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await (await browser.newContext()).newPage();
  for (const pat of ['**/api/image','**/api/bfl-kontext','**/api/get-parent-images','**/api/replicate**','**/api/fal**'])
    await page.route(pat, r => r.fulfill({ status:500, contentType:'application/json', body:'{"error":"blocked"}' }));
  const logs = [];
  page.on('console', m => { const t=m.text(); if (/\[BOOK2|\[ISSUE-CONTINUITY\]|\[PREF-APPLY\]|\[PREF-RESOLVE\]|\[CG-PREF-CHAIN\]/i.test(t)) { logs.push(t.slice(0,200)); log('  >', t.slice(0,150)); }
    else if (/GEN-FAIL|BOOK2.*failed|callChat|Generation failed/i.test(t)) log('  ..', t.slice(0,110)); });

  await page.goto('http://localhost:3000/', { waitUntil:'domcontentloaded', timeout:30000 });
  await page.waitForFunction(() => window.state && typeof window.startBook2==='function' && typeof window._applyRememberedPreferences==='function', { timeout:40000 });
  await page.waitForTimeout(600);

  await page.evaluate((cliff) => {
    const s = window.state;
    window._devBypass = true;
    window._book2TestBypass = true; window._book2TestContinuity = cliff;
    s.subscribed=true; s.fortunes=9999999; s.access='sub';
    // ── simulate a COMPLETED Book 1 (billionaire affair, Mara & Dorian) ──
    s.picks = s.picks || {};
    s.picks.world='billionaire'; s.picks.flavor='affair'; s.picks.dynamic='enemies_to_lovers'; s.picks.worldSubtype='billionaire_modern';
    s.picks.tone='Charged'; s.picks.genre='contemporary';
    s.picks.identity = { playerName:'Mara', partnerName:'Dorian', displayPlayerName:'Mara', displayPartnerName:'Dorian' };
    s.world='billionaire'; s.worldSubtype='billionaire_modern'; s.flavor='billionaire_modern'; s.dynamic='enemies_to_lovers';
    s.storyLength='affair'; s.tier='affair'; s.intensity='Steamy';
    s.gender='Female'; s.loveInterest='Male'; s.authorPronouns='She/Her';
    s.loveInterestName='Dorian'; s.name='Mara'; s.playerName='Mara'; s.partnerName='Dorian'; s.pov='first_person';
    s.storyId='book1-story-id'; s.book_number=1; s.turnCount=6;
    s.renderMode='literary'; s.storyModality='literary'; s.currentEngine='literary';
    s.immutableTitle='Exposed Petals';
    s.sysPrompt = 'You are S. Tory Bound, writing an adult contemporary billionaire romance.';
    s.book1_continuity_summary = cliff;             // pre-set so the bypass uses it
    // relationship progression to carry (they kissed — together-ish, high intimacy)
    s.relationship_phase='together'; s.relationshipPhase='together'; s.intimacyPhase=true;
    s.storySpine = { shape:'enemies_to_lovers', arc:'exposure_to_trust' };
    // remembered preferences (Issue 1 answers): direct expression, relationship-leaning — high confidence, same series
    try{localStorage.removeItem('sb_reader_pref_v1')}catch(_){}
    s.series_id='cont-series-1'; s.issueIndexInRun=1;
    s._prefMemory = {
      demand_hint:       { value:'direct',       confidence:0.8, source:'probe', storyId:'book1-story-id', seriesId:'cont-series-1', lastAskedIssue:1, lastUsedIssue:1, ctx:{} },
      goal_relationship: { value:'relationship', confidence:0.8, source:'micro_decision', storyId:'book1-story-id', seriesId:'cont-series-1', lastAskedIssue:1, lastUsedIssue:1, ctx:{} }
    };
    s.scene1DirectnessSignal=null; s.directnessScore=0;   // prove startBook2's _applyRememberedPreferences re-derives it
    // startBook2 captures const lockedChars = state.main_characters_locked at its TOP (before the archive),
    // so it must be a valid object BEFORE the call (the bypass fills it too late for that capture).
    s.main_characters_locked = { playerName:'Mara', partnerName:'Dorian', displayPlayerName:'Mara', displayPartnerName:'Dorian',
      playerGender:'Female', partnerGender:'Male', playerPronouns:'She/Her', partnerPronouns:'He/Him' };
    s.archetype = { primary:'DARK_VICE', modifier:null, bound:false };
  }, CLIFF);

  log('[CONT] firing real startBook2() …');
  await page.evaluate(async () => { try { await window.startBook2(); } catch(e){ console.log('BOOK2-THREW '+(e&&e.message||'').slice(0,120)); } });

  // wait for the Book-2 Scene-1 prose to be stashed
  const t0=Date.now(); let body=null;
  while (Date.now()-t0 < 300000) {
    await page.waitForTimeout(4000);
    const st = await page.evaluate(() => ({ body: window.state._book2TestSceneBody || null, issue: window.state.issueIndexInRun,
      sig: window.state.scene1DirectnessSignal, memKeys: window.state._prefMemory?Object.keys(window.state._prefMemory):[], rel: window.state.relationship_phase, intim: window.state.intimacyPhase, title: window.state.immutableTitle }));
    if (st.body && st.body.length > 200) { body = st; break; }
    if (Date.now()-t0 > 25000 && !st.body) { /* keep waiting through the ~3 LLM calls */ }
  }

  const result = { checks:{}, prose:null, logs };
  if (body) {
    const txt = body.body;
    result.prose = txt;
    result.state = { issueIndexInRun: body.issue, scene1DirectnessSignal: body.sig, prefMemoryKeys: body.memKeys, relationship_phase: body.rel, intimacyPhase: body.intim, title: body.title };
    const lower = txt.toLowerCase();
    result.checks.scene1_generated = txt.length > 200;
    result.checks.issue_bumped_to_2 = body.issue === 2;
    result.checks.memory_carried = body.memKeys.includes('demand_hint') && body.memKeys.includes('goal_relationship');
    result.checks.silent_apply_applied = body.sig === 'direct';
    result.checks.relationship_carried = body.rel === 'together' && body.intim === true;
    // continuity: references at least one cliffhanger token
    const hits = CONT_TOKENS.filter(tk => lower.includes(tk.toLowerCase()));
    result.checks.continuity_tokens = hits;
    result.checks.continues_cliffhanger = hits.length >= 1;
    // no deck / no backstory re-intro
    result.checks.no_tarot_deck = !/tarot|great-grandmother|the cards|the deck/i.test(txt);
    result.checks.no_didnt_remember_bringing = !/didn'?t remember bringing/i.test(txt);
    // F1: X-or-Y axis-shaped question in prose
    const xy = (txt.match(/[""“][^""“”]{6,90}\bor\b[^""“”]{2,70}\?[""”]|(?:^|\n)\s*[A-Z][^.\n?]{6,90}\bor\b[^.\n?]{2,70}\?/g)||[]).map(s=>s.replace(/\n/g,' ').trim());
    result.checks.f1_xy_questions = xy;
    result.checks.f1_clean = xy.length === 0;
  } else {
    result.checks.scene1_generated = false;
  }

  await browser.close();
  fs.writeFileSync(OUT, JSON.stringify(result, null, 1));
  const c = result.checks;
  const line=(n,v)=>log(`  ${v?'✓':'✗'}  ${n}`);
  log('\n=== REAL BOOK-2 CONTINUITY AUDIT ===');
  line('Book-2 Scene-1 generated (real startBook2 path)', c.scene1_generated);
  line('issueIndexInRun bumped to 2', c.issue_bumped_to_2);
  line('_prefMemory carried across the boundary', c.memory_carried);
  line('silent_apply re-derived scene1DirectnessSignal=direct', c.silent_apply_applied);
  line('relationship (together/intimate) carried, not reset to strangers', c.relationship_carried);
  line('CONTINUES the cliffhanger (token hit: '+JSON.stringify(c.continuity_tokens)+')', c.continues_cliffhanger);
  line('No tarot deck / grandmother re-intro (correct for continuation)', c.no_tarot_deck);
  line('No "didn\'t remember bringing it" opener template', c.no_didnt_remember_bringing);
  line('F1: no X-or-Y axis question leaked into prose', c.f1_clean);
  if (result.prose) log('\n  --- Book-2 Scene-1 opening (first 500 chars) ---\n  ' + result.prose.slice(0,500).replace(/\n+/g,'\n  '));
  log(`\nWROTE ${OUT}`);
  log(`RESULT: ${c.scene1_generated ? 'CONTINUITY RUN COMPLETE — inspect table above + JSON' : '✗ Scene-1 did not generate (inspect logs)'}`);
})().catch(e=>{ console.error('DRIVER-ERR', e.message); process.exit(1); });
