const { chromium } = require('playwright-core');
const fs=require('fs');
const OUT='/private/tmp/claude-501/-Users-romantsukerman-storybound-app/a08d0758-843c-4e0e-a5e2-c3f532b66c76/scratchpad/verify';
const WHO='THE PERSON (a walk-on the reader meets for one sentence):\n- Role: night bartender at a hotel bar that empties out after midnight.\n- Standing: everyone\'s confessor, nobody\'s friend.\n- Right now: close out a slow shift without anyone leaving worse than they came in.\n- What it costs him: he cannot stand watching someone drink alone in silence; he needs to read a person before they have decided whether to talk.';
const SCENE='Just past 1 a.m., a lone guest takes the stool at the far dark end of the bar.';
const GEN='You are imagining a specific real person. Do NOT analyze him, do NOT be literary, do NOT name a trait.\n\n'+WHO+'\n\nSCENE: '+SCENE+'\n\nGive TWENTY DIFFERENT single-sentence things this bartender might actually do or say in this moment — each a distinct, concrete possibility, all TRUE of him. VARY what each reveals (his read of people, his craft, the bar, the guest, his fatigue, his history, his standing) and vary the SCALE (some tiny, some a whole gesture or line). Do NOT make them variations of one move. Output ONLY a numbered list 1-20, one per line.';
const EDIT4='Below are 20 true things a night bartender might do in this moment. The story gets ONE sentence to describe this man. Pick the one that best DEMONSTRATES HIS CHARACTERISTIC COMPETENCE — the particular skill he instinctively reaches for to navigate his world.\n\nTHE TEST (competence, not observation): pick the sentence showing a mastery that is unmistakably HIS. Reject any competence that almost everyone has (suppressing fatigue, staying composed, being tidy, testing equipment) — those are universal, not characteristic. Reject sentences that merely convey facts he is not DOING anything with (trivia). Favor the one where he silently SOLVES A PROBLEM in his domain that only this man — this good at this exact thing — could solve: a random bartender could not do it, a waiter could not, a therapist could not. That unswappable mastery is the point, even if the mastery is small or misplaced.\n\nOutput EXACTLY:\nPICK: <number>\nRUNNERS_UP: <two other numbers>';
(async()=>{
  const b=await chromium.launch({headless:true,channel:'chrome'});
  const p=await (await b.newContext()).newPage();
  await p.goto('http://localhost:3000/',{waitUntil:'domcontentloaded',timeout:30000});
  await p.waitForFunction(()=>window.state,{timeout:30000});
  const call=(sys,user,tok,temp)=>p.evaluate(async({sys,user,tok,temp})=>{const r=await fetch('/api/proxy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'system',content:sys},{role:'user',content:user}],role:'SPECIALIST_RENDERER',preferredModel:'grok-4-1-fast-non-reasoning',temperature:temp,max_tokens:tok})});const j=await r.json();return String((j.choices&&j.choices[0]&&j.choices[0].message&&j.choices[0].message.content)||j.content||'').trim();},{sys,user,tok,temp});
  const raw=await call(GEN,'The twenty:',900,1.05);
  const cands=raw.split('\n').map(l=>l.replace(/^\s*\d+[.)]\s*/,'').trim()).filter(l=>l.length>6).slice(0,20);
  const numbered=cands.map((c,i)=>(i+1)+'. '+c).join('\n');
  const pick=await call(EDIT4,numbered+'\n\nYour choice:',60,0.4);
  fs.writeFileSync(OUT+'/editor_selection_bartender.json',JSON.stringify({candidates:cands,editor:pick},null,2));
  await b.close();process.exit(0);
})().catch(e=>{console.error('ERR',e.message);process.exit(1);});
