import base64, json, urllib.request, urllib.error, time
OUT="/private/tmp/claude-501/-Users-romantsukerman-storybound-app/f8f628bd-81c8-49d1-a1cd-f0b7bc1b48ee/scratchpad/dashscope_compare"
RT=OUT+"/refs2"
def b64(p): return base64.b64encode(open(p,"rb").read()).decode()

legend=("REFERENCE IMAGES (in THIS order; match the trait named; do NOT copy their aspect ratio): "
 "1) RYO TORO STYLE MASTER — match linework, angular contour, rendering density, shading. "
 "2) VEILWEAVE — the many-folded glowing filament-net veil over a nude barefoot body (the face-mask area is DENSE/OPAQUE, and the hips/thighs region is OPAQUE, per text).\n\n")
STYLE=("STYLE — Ryo Toro (match the RYO TORO STYLE MASTER ref): lush, RICHLY RENDERED manga illustration — confident angular ink linework WITH intricate fine detail; layered ink + painterly shading; rendered texture on skin, hair, fabric and metal; dense decorative detail; dramatic high contrast, deep blacks, warm sepia backlight. A drawn full-colour illustration, NOT a photo, NOT 3D. MAXIMISE detail — a gallery-quality character portrait.\n\n")
FORMAT=("FORMAT: a SINGLE TALL PORTRAIT of ONE figure — a dramatic gallery-quality CHARACTER-INTRODUCTION splash (full body or three-quarter length, a poised heroic stance). ONE single image, NOT a grid, NOT multiple panels. No caption text, no lettering, no watermark.\n\n")
SUBJECT=("SUBJECT — KAEL, a First Favored: tall, athletic, silver-white hair, HOOD UP; a poised, watchful heroic stance in the Veilwood, THE ANSWER held ready.\n"
 "VEILWEAVE: a sheer, hooded, MANY-FOLDED veil woven from a luminous iridescent FILAMENT-NET. The glowing filament-NET WEAVE must be CLEARLY, PROMINENTLY VISIBLE across the ENTIRE veil — a dense fine web of criss-crossing luminous thread-lines studded with sparkling light-NODES, covering the whole garment (hood, torso, arms, legs, every fold). This net is the defining feature — NOT faint, NOT reduced to a few smooth streaks, NOT a plain smooth white sheen. In MANY soft folds (like the reference — NOT tattered, NOT a plain cloak, NOT a grid painted on skin). Beneath the sheer veil he is NUDE and BAREFOOT — NO undergarment; the bare body reads through the translucent net over the CHEST, ABDOMEN, SHINS and FEET.\n"
 "MODESTY (do this exactly): the SAME filament-net veil continues UNBROKEN across the hips and upper thighs — the identical glowing net WEAVE, the same folds, the same fabric as the rest of the veil — but in that region the net DENSIFIES so it reads OPAQUE (you cannot see the body through it there), then GRADUALLY FADES back to sheer translucence ABOVE the waistline and BELOW mid-thigh: a SMOOTH OPACITY GRADIENT within ONE continuous piece of gossamer, with NO hard edge. The luminous net pattern stays VISIBLE even in the opaque zone — it is the VEILWEAVE ITSELF getting denser there, not a different material. LIGHTING: the opaque zone is lit the SAME as the rest of the veil — since here the wearer is WELL-LIT and the veil glows bright, the dense zone is a soft LUMINOUS WHITE fade (a bright, pale, matte white densification of the same net), NOT a dark patch, NOT a shadow, NOT grey. (General rule for future renders: the dense zone matches the veil's brightness — a WHITE fade when the veil is bright, dark only when the wearer is in darkness.) It stays soft and matte, not glittery. It is NOT a separate wrap, sarong, skirt, sash, loincloth or solid plain-cloth garment; NOT a fitted brief/thong/underwear/waistband; NOT a small patch at the crotch — just the one veil, its net thickening to a pale luminous opaque over the hips and thighs and feathering back out to sheer.\n"
 "He refracts into about FIVE-to-SIX overlapping misregistered WHOLE copies drifting around him (his signature effect), each identical — and EVERY copy holds its OWN identical THE ANSWER polearm in hand (all the figures are armed with the same weapon, NOT just the central one; no copy is empty-handed).\n"
 "FACE (Mystery Man): EYES VISIBLE and expressive (pale silver eyes). NOSE and MOUTH covered by a half-mask of the SAME filament-net, but over the face the weave is DENSE, PACKED and OPAQUE — a SOLID luminous mask that FULLY HIDES the nose and mouth (cannot be seen through). Only the eyes show, above the opaque mask. Same on every copy.\n"
 "THE ANSWER (Kael's weapon): a long POLEARM with a DEEP HOOK at EACH end (both ends identical), each hook curled like a QUESTION MARK — the curve wraps far enough around to physically CATCH and hold a limb or a neck (a true grappling hook, not a shallow curve). Each hook's OUTER edge is a sharp curved BLADE; each hook's INNER curve is SERRATED with saw-teeth to grip. NEVER a straight spear, trident, or plain sword.\n\n")
SETTING=("SETTING: the VEILWOOD at dusk behind him — white trees grown as MATED PAIRS (TWO pale-white trunks BRAIDED around each other into a twisted double-helix, never one gnarled trunk), long white weeping-willow veil-fronds, ground of deep-CRIMSON grass growing in MATED BRAIDS (pairs of blades twisting AROUND each other like braided rope, NOT single spiral coils), warm backlight, scattered glowing motes / soft bokeh points of light.\n\n")
AVOID=("AVOID: a separate wrapped sarong, skirt, sash, loincloth or any solid plain-cloth garment over the hips (it is the SAME sheer glowing net veil, just DENSER/opaque there, with the net pattern still visible); a HARD edge between the opaque and sheer zones (it is a SMOOTH gradient); the opaque area looking like a different fabric or material from the rest of the veil; a DARK opaque zone or a dark shadow over the hips/thighs while the veil and figure are brightly lit (when the veil is bright the dense zone is a soft LUMINOUS WHITE fade, never dark or grey); a small opaque patch, triangle or brief ONLY at the crotch; a brief, thong, underwear, loincloth or waistband; a sparkling/glittering/bright/glowing groin; a sheer/see-through mask revealing the nose or mouth (the mask is DENSE and OPAQUE over the face); a visible nose or mouth; a blank/shadow-void face (eyes must show); pants, shorts, boots, shoes or footwear (BAREFOOT); a plain smooth cloak with no visible net-weave; a tattered/ragged veil; the veil as just a grid on skin; shallow or barely-curved hook ends (they are DEEP question-mark hooks); the filament-net weave faint, missing, or reduced to a few smooth streaks (it must be a DENSE, clearly VISIBLE glowing web across the whole veil); any refracted copy with EMPTY hands or no weapon (EVERY copy holds an identical The Answer); THE ANSWER as a straight spear/trident/plain sword; a grid or multiple panels; more than one primary figure; caption text, lettering, watermark; single spiral-coil grass; a single un-braided tree trunk; flat low-detail rendering.")
full=legend+STYLE+FORMAT+SUBJECT+SETTING+AVOID

refs=[{"b64":b64(RT+"/style_hi.jpg"),"label":"RYO TORO STYLE MASTER"},{"b64":b64(RT+"/veilweave_net.jpg"),"label":"VEILWEAVE"}]
body=json.dumps({"provider":"gemini","model":"gemini-3.1-flash-image-preview","imageIntent":"scene",
  "prompt":full,"reference_images_b64":refs,"textFirst":True,"imageSize":"4K","aspect_ratio":"3:4","size":"3072x4096","n":1}).encode()
print("payload %.2fMB chars=%d"%(len(body)/1048576,len(full)))
for attempt in (1,2,3):
    req=urllib.request.Request("http://localhost:3000/api/image",data=body,headers={"Content-Type":"application/json"})
    t=time.time()
    try:
        d=json.loads(urllib.request.urlopen(req,timeout=300).read()); url=d.get("url","")
        if url.startswith("data:"):
            open(OUT+"/kael_solo.png","wb").write(base64.b64decode(url.split(",",1)[1])); print("OK %.1fs -> kael_solo.png"%(time.time()-t)); break
        elif url.startswith("http"):
            img=urllib.request.urlopen(url,timeout=180).read(); open(OUT+"/kael_solo.png","wb").write(img); print("OK %.1fs %dKB"%(time.time()-t,len(img)//1024)); break
        else: print("NO IMAGE:",json.dumps(d)[:300])
    except urllib.error.HTTPError as e: print("HTTP %s (attempt %d): %s"%(e.code,attempt,e.read()[:200]))
    except Exception as e: print("ERR (attempt %d): %s"%(attempt,e))
print("DONE")
