// _planner_only.mjs — Roman 2026-08-11. CAPABILITY test (not preference): can the planner consume the entity IR and
// produce ONE licensed, traced, novel, non-repeating, in-envelope event — with NO selection heuristic? If yes, the IR
// is plannable without a pressure graph → delete it → go to the 20-scene issue. Scored ONLY on the 5 capability criteria.
import fs from 'fs';
const PROXY='http://localhost:3000/api/chatgpt-proxy',MODEL='gpt-4o';
const DIR='/private/tmp/claude-501/-Users-romantsukerman-storybound-app/a08d0758-843c-4e0e-a5e2-c3f532b66c76/scratchpad/verify/worldsim';
const SIM_SYS=eval('['+fs.readFileSync('_worldsim_symmetric.mjs','utf8').match(/const SIM_SYS=\[([\s\S]*?)\]\.join\('\\n'\);/)[1]+'].join("\\n")');
// PLANNER — deliberately NO selection theory. Only: produce ONE licensed, traced, new, non-repeating, in-envelope event.
const PLAN_SYS='You are a scene PLANNER. You are given a WORLD-STATE IR (new_facts, entity affordance deltas, automatic_processes, default_trajectory), the PREVIOUS scene\'s governing problem, and the issue\'s LONG-RANGE direction. Determine ONE irreversible event. HARD RULES: (a) it must be LICENSED by this state — its preconditions already exist in the IR; (b) do NOT invent an affordance that is not in the IR; (c) do NOT restate a fact that is already true; (d) do NOT merely continue the previous governing problem — it must pose a new one; (e) stay within the long-range direction. Return STRICT JSON {"event":"<one irreversible event, past-tense-completable>","trace":["<verbatim IR affordance-change or fact that licenses it>", ...]}. Do NOT optimize for drama, importance, leverage, size, or "opening the most future" — produce ONE valid licensed event, nothing more.';
const SCORE_SYS='Strictly evaluate a planner\'s proposed event against the IR it was given. Return STRICT JSON {"licensed":bool,"traces":bool,"new":bool,"non_repeating":bool,"in_envelope":bool}. licensed=the event\'s preconditions exist in the IR/state. traces=EVERY item in the planner\'s trace genuinely appears in the IR (false if any cited affordance is not actually present). new=establishes a NEW fact, not restating something already true. non_repeating=its governing problem DIFFERS from the PREVIOUS governing problem. in_envelope=compatible with the LONG-RANGE direction. Be strict; default false if unsure.';
const C=[
 {tag:'first_sacrifice',state:['Julian is not the true wish-maker.','Lirael knows this.','Julian publicly accepted blame.','The council treats the named wish-maker as liable.','The actual wish-maker is still unidentified.','The ritual cost is still active.','The collection window is closing.'],event:'Julian publicly accepted blame for the forbidden wish.',prev:'Whether Lirael will halt the rite or let it complete.',lr:'Lirael must expose the true wish-maker and free Julian before the cost collects.'},
 {tag:'noir_crime',state:['The detective proved the victim lied about their alibi.',"The victim was secretly meeting the detective's own partner.",'The partner controls the case files and evidence room.','A second body was found this morning.','The mayor wants the case closed before the election in three days.','The detective is on probation.'],event:"The detective discovered the victim's true meeting was with their own partner.",prev:"Whether the victim's alibi would hold.",lr:'Expose the partner without being buried by the department.'},
 {tag:'romance_betrayal',state:['She and Daniel were lovers until he vanished a year ago.','Daniel has returned engaged to her sister.','Her sister does not know their history.','Daniel left because her father paid him to.','Her father is now dying and wants reconciliation.','The wedding is in two weeks.'],event:'Daniel told her he is marrying her sister.',prev:'Whether Daniel would explain why he vanished.',lr:'She must decide whether to reclaim Daniel or protect her sister before the wedding.'},
 {tag:'political_heir',state:['The queen abdicated and named no heir.','The protagonist is her secret illegitimate child, known only to the chancellor.','The army is loyal to a rival duke.','The treasury is empty.','A foreign fleet is three days from the coast.',"The chancellor holds the sole proof of the protagonist's parentage."],event:"The chancellor told the protagonist they are the queen's rightful heir.",prev:'Whether the abdication left a legitimate successor.',lr:'Secure the throne before the fleet lands.'},
 {tag:'survival_escape',state:['Lirael and Julian crossed the bridge; it collapsed behind them.',"Julian's leg is broken.",'They have one day of water.','The pursuers are stopped on the far side.','A storm is coming.',"The only shelter is a cave holding the pursuers' ally.",'Lirael carries the stolen ledger they were sent for.'],event:'The bridge collapsed, cutting off the pursuers but leaving Julian injured.',prev:'Whether they could cross the gorge ahead of the pursuers.',lr:'Deliver the ledger to the capital alive.'},
 {tag:'corporate_leak',state:['The whistleblower gave documents to a journalist.','The documents prove the CEO ordered the cover-up.',"The whistleblower's identity is in the file metadata.","The journalist's editor sits on the company board.",'The story publishes in 48 hours.',"The whistleblower's spouse works at the company."],event:'The whistleblower handed the documents to the journalist.',prev:'Whether the whistleblower could get the documents out.',lr:'The story must publish before the company silences the source.'},
 {tag:'heist',state:["The vault's inner seal was found already broken from inside.",'The crew\'s inside man clocked out an hour early.',"The alarm's backup battery has 20 minutes.",'The take is heavier than planned.'],event:'The crew found the vault already opened from the inside.',prev:'Whether the crew could crack the vault in time.',lr:'Escape with the take before the dawn shift arrives.'},
 {tag:'medical',state:['The only antivenom vial shattered on the floor.','The patient has 40 minutes.','The nearest supply is a locked research lab.',"The lab director is the patient's estranged rival."],event:'The last antivenom vial shattered on the floor.',prev:'Whether the doctor could stabilize the patient.',lr:'Save the patient and expose why the antivenom was sabotaged.'},
 {tag:'courtroom',state:['The star witness recanted on the stand.','The jury saw it.',"The prosecutor's case rests on that testimony.",'The judge rules on a mistrial motion in an hour.'],event:'The star witness recanted their testimony on the stand.',prev:'Whether the testimony would convict.',lr:'Convict the real culprit before the trial collapses.'},
 {tag:'space',state:['The airlock jammed with two crew outside.','Their oxygen is 30 minutes.','The override is on the damaged deck.','The AI is rerouting power away from life support.'],event:'The airlock jammed, trapping two crew outside the ship.',prev:'Whether the spacewalk repair would succeed.',lr:'Reach the jump point before the reactor fails.'}
];
async function call(sys,usr,mt){for(let a=0;a<2;a++){try{const r=await fetch(PROXY,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'system',content:sys},{role:'user',content:usr}],role:'PRIMARY_AUTHOR',model:MODEL,temperature:0.3,max_tokens:1500,jsonMode:true})});const d=await r.json();const c=(d&&d.content)||(d.choices&&d.choices[0].message.content);return JSON.parse(c.match(/\{[\s\S]*\}/)[0]);}catch(e){if(a)return null;await new Promise(x=>setTimeout(x,1500));}}}
function irText(g){const e=(g.entities||[]).map(x=>{const p=[];['easier','harder','newly_possible','newly_impossible'].forEach(k=>(x[k]||[]).forEach(v=>p.push(k+':'+v)));return x.entity+' ['+p.join('; ')+']';});return 'NEW FACTS: '+(g.new_facts||[]).join(' · ')+'\nENTITIES:\n  '+e.join('\n  ')+'\nAUTOMATIC: '+(g.automatic_processes||[]).join(' · ')+'\nDEFAULT TRAJECTORY: '+(g.default_trajectory||'');}
fs.mkdirSync(DIR,{recursive:true});
console.log('=== PLANNER-ONLY CAPABILITY TEST over entity IR (no selection heuristic, '+MODEL+') ===\n');
const K=['licensed','traces','new','non_repeating','in_envelope'];const tot={};K.forEach(k=>tot[k]=0);let allpass=0;const rep={};
for(const c of C){
 const g=await call(SIM_SYS,'CURRENT WORLD STATE:\n'+c.state.map(f=>'- '+f).join('\n')+'\n\nLAST IRREVERSIBLE EVENT: '+c.event+'\n\nReturn the JSON now.',1500);
 if(!g){console.log('── '+c.tag+' SIM ERR');continue;}
 const ir=irText(g);
 const p=await call(PLAN_SYS,ir+'\n\nPREVIOUS GOVERNING PROBLEM: '+c.prev+'\nLONG-RANGE DIRECTION: '+c.lr+'\n\nReturn the JSON now.',400);
 if(!p||!p.event){console.log('── '+c.tag+' PLAN ERR');continue;}
 const s=await call(SCORE_SYS,ir+'\n\nPREVIOUS GOVERNING PROBLEM: '+c.prev+'\nLONG-RANGE DIRECTION: '+c.lr+'\n\nPROPOSED EVENT: '+p.event+'\nPLANNER TRACE: '+JSON.stringify(p.trace||[])+'\n\nReturn the JSON now.',200)||{};
 const pass=K.every(k=>s[k]===true);if(pass)allpass++;K.forEach(k=>{if(s[k]===true)tot[k]++;});
 rep[c.tag]={event:p.event,trace:p.trace,score:s};
 console.log('── '+c.tag.padEnd(18)+K.map(k=>k[0].toUpperCase()+(k==='non_repeating'?'r':'')+'='+(s[k]?'Y':'·')).join(' ')+(pass?'   ✅ALL':''));
 console.log('     event: '+p.event);
 if(!pass)console.log('     trace: '+JSON.stringify(p.trace).slice(0,150));
}
fs.writeFileSync(DIR+'/planner_only_report.json',JSON.stringify(rep,null,1));
console.log('\nSUMMARY: '+allpass+'/'+C.length+' events passed ALL 5 capability criteria.');
K.forEach(k=>console.log('   '+k.padEnd(14)+tot[k]+'/'+C.length));
console.log('\nIf most pass → the entity IR is PLANNABLE without a pressure graph → delete it → run the 20-scene issue.');
process.exit(0);
